"""add secondary genres to movie

Revision ID: 14afb16aea10
Revises: 01da13dcb959
Create Date: 2026-08-14 11:26:43.929347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14afb16aea10'
down_revision: Union[str, Sequence[str], None] = '01da13dcb959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('genre_2', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('genre_3', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'genre_3')
    op.drop_column('movies', 'genre_2')
    # ### end Alembic commands ###
