"""add movie library

Revision ID: 23d7f77bf1b9
Revises: 14afb16aea10
Create Date: 2026-08-21 16:31:09.435905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d7f77bf1b9'
down_revision: Union[str, Sequence[str], None] = '14afb16aea10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movie_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_user_movie_library_user_movie')
    )
    op.create_index(op.f('ix_user_movie_library_movie_id'), 'user_movie_library', ['movie_id'], unique=False)
    op.create_index(op.f('ix_user_movie_library_user_id'), 'user_movie_library', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_movie_library_user_id'), table_name='user_movie_library')
    op.drop_index(op.f('ix_user_movie_library_movie_id'), table_name='user_movie_library')
    op.drop_table('user_movie_library')
    # ### end Alembic commands ###
