"""add daily quiz models and user streak

Revision ID: 304b3673cbac
Revises: 4bf6083c2e66
Create Date: 2026-07-29 13:09:10.698744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304b3673cbac'
down_revision: Union[str, Sequence[str], None] = '4bf6083c2e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bonus_points', sa.Integer(), server_default='30', nullable=False),
    sa.Column('perfect_bonus', sa.Integer(), server_default='10', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quizzes_date'), 'daily_quizzes', ['date'], unique=True)
    op.create_table('daily_quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_quiz_id', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('bonus_earned', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('current_question', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['daily_quiz_id'], ['daily_quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quiz_attempts_daily_quiz_id'), 'daily_quiz_attempts', ['daily_quiz_id'], unique=False)
    op.create_index(op.f('ix_daily_quiz_attempts_user_id'), 'daily_quiz_attempts', ['user_id'], unique=False)
    op.create_table('daily_quiz_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_quiz_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_quiz_id'], ['daily_quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quiz_movies_daily_quiz_id'), 'daily_quiz_movies', ['daily_quiz_id'], unique=False)
    op.add_column('users', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_daily_completed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_daily_completed_date')
    op.drop_column('users', 'current_streak')
    op.drop_index(op.f('ix_daily_quiz_movies_daily_quiz_id'), table_name='daily_quiz_movies')
    op.drop_table('daily_quiz_movies')
    op.drop_index(op.f('ix_daily_quiz_attempts_user_id'), table_name='daily_quiz_attempts')
    op.drop_index(op.f('ix_daily_quiz_attempts_daily_quiz_id'), table_name='daily_quiz_attempts')
    op.drop_table('daily_quiz_attempts')
    op.drop_index(op.f('ix_daily_quizzes_date'), table_name='daily_quizzes')
    op.drop_table('daily_quizzes')
    # ### end Alembic commands ###
