"""add country field to movie

Revision ID: 4bf6083c2e66
Revises: ef953e38ff30
Create Date: 2026-07-29 11:10:24.524714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf6083c2e66'
down_revision: Union[str, Sequence[str], None] = 'ef953e38ff30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('country', sa.String(length=20), server_default='foreign', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'country')
    # ### end Alembic commands ###
