"""add featured movies

Revision ID: 5f7d02851f5b
Revises: be96ec3e69d5
Create Date: 2026-08-26 14:37:27.529497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7d02851f5b'
down_revision: Union[str, Sequence[str], None] = 'be96ec3e69d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_featured_movies_date')
    )
    op.create_index(op.f('ix_featured_movies_date'), 'featured_movies', ['date'], unique=False)
    op.create_index(op.f('ix_featured_movies_movie_id'), 'featured_movies', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_featured_movies_movie_id'), table_name='featured_movies')
    op.drop_index(op.f('ix_featured_movies_date'), table_name='featured_movies')
    op.drop_table('featured_movies')
    # ### end Alembic commands ###
