"""add movie reactions

Revision ID: 77d27ed7b708
Revises: 23d7f77bf1b9
Create Date: 2026-08-21 17:18:02.677219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d27ed7b708'
down_revision: Union[str, Sequence[str], None] = '23d7f77bf1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_movie_reaction_user_movie')
    )
    op.create_index(op.f('ix_movie_reactions_movie_id'), 'movie_reactions', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_reactions_user_id'), 'movie_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_reactions_user_id'), table_name='movie_reactions')
    op.drop_index(op.f('ix_movie_reactions_movie_id'), table_name='movie_reactions')
    op.drop_table('movie_reactions')
    # ### end Alembic commands ###
